import {
    Button,
    ScrollView,
    VerticalBox,
    StandardTableView,
    ListView,
    CheckBox,
    TextEdit,
    LineEdit,
    TabWidget,
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";
import {
    TextButton,
    MaterialWindow,
    Modal,
    PopupMenu,
    Vertical,
    Horizontal,
    HorizontalDivider,
    OutlinedCard,
    ElevatedCard,
    FilledCard,
    ListTile,
    ModalDrawer,
    NavigationRail,
    ElevatedButton,
    FilledButton,
    NavigationBar,
    SmallAppBar,
    AppBar,
    TabBar,
} from "../material.slint";
import { ModalWindow } from "modal-window.slint";
import { CredsStruct, UIGlobal } from "global.slint";
import { TextField } from "components/text_field.slint";
import { NavigationDrawer } from "components/navigation_drawer.slint";


component Space inherits Rectangle {
    height: 100px;
}

component CredsComponentSidebar inherits Rectangle {
    border-width: 2px;
    border-color: #565656;
    border-radius: 4px;
    in property <string> VaultName;
    VerticalLayout {
        padding: 10px;
        Text {
            text: root.VaultName;
        }
    }
}

component CredsComponent inherits ListView {
    callback copy_requested(id: string);
    // in property <[CredsStruct]> items: [{ name: "Discord", password: "Password" }];
    in property <color> color;

    for item in UIGlobal.creds: HorizontalLayout {
        CheckBox {
            toggled => {
                copy_requested(item.id);
                // ! >> Callback to Rust Code >>
            }
            text: item.name;
        }

        Text {
            text: item.password;
        }
    }
}

export { UIGlobal }

export component AppWindow inherits MaterialWindow {
    preferred-width: 500px;
    always-on-top: false;
    disable-hover: false;
    preferred-height: 450px;
    title: "Credentials";
    in-out property <bool> showModal: false;
    VerticalBox {
        max-width: parent.preferred-width;
        padding: 20px;
        // Main Content
        FilledCard {
            VerticalLayout {
                height: parent.height;
                padding-left: 16px;
                padding-right: 16px;
                spacing: 12px;
                alignment: start;

                Space {
                    height: 10px;
                }

                HorizontalLayout {
                    alignment: start;
                    spacing: 10px;
                    Text {
                        text: "Credentials";
                        font-size: 22px;
                    }

                    FilledButton {
                        text: "+ Creds";
                        // width: 10%;
                        clicked => {
                            modal.visible = true;
                            modal.service_url = "";
                            modal.service_password_value = "";
                            modal.service_email_username = "";
                        }
                    }

                    FilledButton {
                        text: "New Vault";
                        clicked => {
                            UIGlobal.new_vault();
                        }
                    }

                    FilledButton {
                        clicked => {
                            UIGlobal.load();
                        }
                        text: "Load Vault";
                    }

                    FilledButton {
                        text: "Save Vault";
                        clicked => {
                            UIGlobal.save();
                        }
                    }
                }

                CredsComponent {
                    height: 100%;
                    copy_requested(id) => {
                        UIGlobal.cb_copy(id);
                    }
                }

                Space { }
            }
        }
    }

    modal := ModalWindow {
        visible: true;
    }
}
