import {
    Button,
    ScrollView,
    VerticalBox,
} from "std-widgets.slint";

component CredsComponentSidebar inherits Rectangle {
    border-width: 2px;
    border-color: #565656;
    border-radius: 10px;
    VerticalLayout {
        padding: 10px;
        Text {
            text: "Vault Name";
            color: #ffffff;
        }
    }
}

component CredsComponent inherits Rectangle {
    border-width: 2px;
    border-color: #565656;
    border-radius: 10px;
    VerticalLayout {
        padding: 10px;
        Text {
            text: "Name: ";
            color: #ffffff;
        }

        Text {
            text: "Value: ";
            color: #ffffff;
        }
    }
}

export component AppWindow inherits Window {
    // width: 700px;
    height: 450px;
    background: #1e1e1e;
    HorizontalLayout { 
        // Sidebar
        Rectangle {
            width: 170px;
            // min-width: 100px;
            background: #252525;
            layout := VerticalLayout {
                alignment: start;
                padding: 16px;
                spacing: 20px;
                Text {
                    text: "Vault";
                    font-size: 26px;
                    color: #ffffff;
                    font-weight: 600;
                }

                Button {
                    text: "+ Add";
                    primary: true;
                    clicked => {
                        // layout.padding += 12px;
                    }
                }

                CredsComponentSidebar { }
            }
        }

        // Main Content
        Rectangle {
            background: #1e1e1e;
            VerticalLayout {
                padding: 16px;
                spacing: 12px;
                Text {
                    text: "Credentials";
                    font-size: 22px;
                    color: #ffffff;
                }

                ScrollView {
                    viewport-height: parent.height - 60px;
                    VerticalLayout {
                        spacing: 8px;
                        // Creds Card Here
                        CredsComponent { }

                        CredsComponent { }

                        CredsComponent { }

                        CredsComponent { }
                    }
                }
            }
        }
    }
}
